# Generated by Django 4.2.3 on 2024-01-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_name_product_product_name_and_more'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarItem',
            new_name='CartItem',
        ),
    ]
