# Generated by Django 4.2.3 on 2024-01-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_caritem_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
