# Generated by Django 4.2.3 on 2024-01-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationmanager'),
        ('carts', '0003_rename_cart_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
